Repository ros2/rosbag2, pull requests merged in 2019-05, with the labels that each got.

#104 use fastrtps static instead of dynamic
  rosbag2_converter_default_plugins/CMakeLists.txt
  rosbag2_converter_default_plugins/package.xml
  rosbag2_converter_default_plugins/src/rosbag2_converter_default_plugins/cdr/cdr_converter.cpp
  rosbag2_tests/CMakeLists.txt
  rosbag2_transport/test/rosbag2_transport/test_rosbag2_node.cpp
Labels: in review

#107 fix logging signature
  rosbag2/include/rosbag2/logging.hpp
  rosbag2_converter_default_plugins/src/rosbag2_converter_default_plugins/logging.hpp
  rosbag2_storage/include/rosbag2_storage/logging.hpp
  rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/logging.hpp
  rosbag2_transport/include/rosbag2_transport/logging.hpp
Labels: bug, in review

#110 fix line length of logging macros
  rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/logging.hpp
Labels: in review

#100 Fix issue with ros2bag record python frontend
  ros2bag/ros2bag/verb/record.py
Labels: in review

#112 Pass CMAKE_TOOLCHAIN_FILE if crosscompiling
  sqlite3_vendor/CMakeLists.txt
Labels: in progress

#111 fix compilation against master
  rosbag2/src/rosbag2/types/introspection_message.cpp
  rosbag2/test/rosbag2/test_sequential_reader.cpp
  rosbag2/test/rosbag2/test_typesupport_helpers.cpp
  rosbag2/test/rosbag2/test_writer.cpp
  rosbag2/test/rosbag2/types/test_ros2_message.cpp
  rosbag2_converter_default_plugins/test/rosbag2_converter_default_plugins/cdr/test_cdr_converter.cpp
  rosbag2_test_common/include/rosbag2_test_common/publisher_manager.hpp
  rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp
  rosbag2_tests/resources/cdr_test/metadata.yaml
  rosbag2_tests/resources/wrong_rmw_test/metadata.yaml
  rosbag2_tests/test/rosbag2_tests/record_fixture.hpp
  rosbag2_tests/test/rosbag2_tests/test_converter.cpp
  rosbag2_tests/test/rosbag2_tests/test_rosbag2_info_end_to_end.cpp
  rosbag2_tests/test/rosbag2_tests/test_rosbag2_play_end_to_end.cpp
  rosbag2_tests/test/rosbag2_tests/test_rosbag2_record_end_to_end.cpp
  rosbag2_transport/src/rosbag2_transport/generic_publisher.cpp
  rosbag2_transport/test/rosbag2_transport/test_play.cpp
  rosbag2_transport/test/rosbag2_transport/test_play_timing.cpp
  rosbag2_transport/test/rosbag2_transport/test_record.cpp
  rosbag2_transport/test/rosbag2_transport/test_record_all.cpp
  rosbag2_transport/test/rosbag2_transport/test_record_all_no_discovery.cpp
  rosbag2_transport/test/rosbag2_transport/test_rosbag2_node.cpp
Labels: bug, in review

#114 Handle message type name with multiple namespace parts
  rosbag2/src/rosbag2/typesupport_helpers.cpp
  rosbag2/test/rosbag2/test_typesupport_helpers.cpp
  rosbag2_transport/test/rosbag2_transport/test_rosbag2_node.cpp
Labels: in review

#115 changes to avoid deprecated API's
  rosbag2_test_common/include/rosbag2_test_common/publisher_manager.hpp
  rosbag2_test_common/include/rosbag2_test_common/subscription_manager.hpp
  rosbag2_transport/test/rosbag2_transport/test_record_all_no_discovery.cpp
  rosbag2_transport/test/rosbag2_transport/test_rosbag2_node.cpp
Labels: in progress

#116 ignore cast function type warning
  rosbag2_transport/src/rosbag2_transport/rosbag2_transport_python.cpp
Labels: in review

#117 fix condition to only apply pragma for GCC 8+
  rosbag2_transport/src/rosbag2_transport/rosbag2_transport_python.cpp
Labels: bug, in review

#118 clean up test dependencies for rosbag2_test_common
  rosbag2_test_common/CMakeLists.txt
  rosbag2_test_common/package.xml
Labels: in review

#120 Update troubleshooting reference to index.ros.org
  rosbag2_transport/rosbag2_transport/__init__.py
Labels: in review

#93 Fixes an init race condition
  rosbag2/include/rosbag2/writer.hpp
  rosbag2/src/rosbag2/writer.cpp
  rosbag2/test/rosbag2/mock_storage.hpp
  rosbag2_storage/include/rosbag2_storage/storage_interfaces/base_write_interface.hpp
  rosbag2_storage/test/rosbag2_storage/test_plugin.cpp
  rosbag2_storage/test/rosbag2_storage/test_plugin.hpp
  rosbag2_storage_default_plugins/include/rosbag2_storage_default_plugins/sqlite/sqlite_storage.hpp
  rosbag2_storage_default_plugins/src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp
  rosbag2_storage_default_plugins/test/rosbag2_storage_default_plugins/sqlite/test_sqlite_storage.cpp
  rosbag2_transport/src/rosbag2_transport/recorder.cpp
Labels: in review
