Repository ros2/rosbag2, pull requests merged in 2019-11, with the labels that each got.

#210 load metadata from storage if no yaml file is found
  rosbag2/src/rosbag2/readers/sequential_reader.cpp
  rosbag2/test/rosbag2/test_multifile_reader.cpp
  rosbag2/test/rosbag2/test_sequential_reader.cpp
Labels: bug

#211 make ros tooling working group maintainer
  ros2bag/package.xml
  rosbag2/package.xml
  rosbag2_converter_default_plugins/package.xml
  rosbag2_storage/package.xml
  rosbag2_storage_default_plugins/package.xml
  rosbag2_test_common/package.xml
  rosbag2_tests/package.xml
  rosbag2_transport/package.xml
  shared_queues_vendor/package.xml
  sqlite3_vendor/package.xml
Labels: in review

#216 [Compression - 1] Create new rosbag2 compression package
  rosbag2_compression/CMakeLists.txt
  rosbag2_compression/package.xml
Labels: needs review
