Repository ros2/rosbag2, pull requests merged in 2020-08, with the labels that each got.

#442 performance testing packages
  ros2bag/pytest.ini
  rosbag2_performance/rosbag2_performance_writer_benchmarking/CMakeLists.txt
  rosbag2_performance/rosbag2_performance_writer_benchmarking/README.md
  rosbag2_performance/rosbag2_performance_writer_benchmarking/include/rosbag2_performance_writer_benchmarking/byte_producer.hpp
  rosbag2_performance/rosbag2_performance_writer_benchmarking/include/rosbag2_performance_writer_benchmarking/message_queue.hpp
  rosbag2_performance/rosbag2_performance_writer_benchmarking/include/rosbag2_performance_writer_benchmarking/writer_benchmark.hpp
  rosbag2_performance/rosbag2_performance_writer_benchmarking/package.xml
  rosbag2_performance/rosbag2_performance_writer_benchmarking/scripts/benchmark.sh
  rosbag2_performance/rosbag2_performance_writer_benchmarking/src/main.cpp
  rosbag2_performance/rosbag2_performance_writer_benchmarking/src/writer_benchmark.cpp
Labels: performance

#508 Document QoS Policy overrides
  README.md
  docs/qos_profile_overrides.md
Labels: documentation

#517 disable sanitizer by default
  rosbag2_cpp/CMakeLists.txt
Labels: bug
